### ISSUE TITLE
This is js not node

### ISSUE THREAD

**Issue by Airfald** [microsoft/beginners-intro-javascript-node#7]
This is js not node

**Comment by jpokan** [comment]
> This is js not node

Hey Airfald, i just watched all the series. It uses node.js to run and test javascript locally. There are some links below the repo where there is a node focused series https://aka.ms/NodeBeginnerSeries
Cheers!

**Comment by GeekTrainer** [comment]
Sorry for any confusion here. The reason it's marked as Node.js in the title is because it uses the Node.js runtime to run the code. This is to separate it from how things run in the browser.
