### ISSUE TITLE
Regarding the name of the series

### ISSUE THREAD

**Issue by Jassi10000-zz** [microsoft/beginners-intro-javascript-node#8]
I have gone through pretty much stuff provided here as I came with the intention of revising my beginner Node.js basics
But what I experienced is that this stuff is mostly JavaScript  and not Node.js as the latter consists of study of modules ,package manager, basic info of API's and all other necessary stuff 

Anyways the content is quite nice and informative
So its my suggestion to please change the repo name and also make respective changes to the Readme , so that I can refer this awesome material to my friends

**Comment by GeekTrainer** [comment]
Sorry for any confusion here. The reason it's marked as Node.js in the title is because it uses the Node.js runtime to run the code. This is to separate it from how things run in the browser.
